Repository ErwanLT/markdownGenerator, pull requests merged in 2020-10, with the labels that each got.

#3 add TasklistItem
  README.md
  markdown/src/main/java/fr/eletutour/markdown/items/tasklist/README.md
  markdown/src/main/java/fr/eletutour/markdown/items/tasklist/TasklistItem.java
  markdown/src/test/java/fr/eletutour/markdown/acceptance/steps/MarkdownGeneratorFileStepsDefinition.java
Labels: enhancement

#11 Added Table item (Issue #4)
  README.md
  markdown/src/main/java/fr/eletutour/markdown/items/table/README.md
  markdown/src/main/java/fr/eletutour/markdown/items/table/Table.java
  markdown/src/test/java/fr/eletutour/markdown/acceptance/steps/MarkdownGeneratorFileStepsDefinition.java
Labels: hacktoberfest-accepted

#12 creation of codacy.yml
  .codacy.yml
Labels: enhancement, good first issue, hacktoberfest-accepted

#18 add bold emphasis
  README.md
  markdown/src/main/java/fr/eletutour/markdown/items/emphasis/Bold.java
  markdown/src/main/java/fr/eletutour/markdown/items/emphasis/README.md
  markdown/src/test/java/fr/eletutour/markdown/acceptance/steps/MarkdownGeneratorFileStepsDefinition.java
Labels: enhancement, good first issue, hacktoberfest-accepted

#19 resolve #15
  README.md
  markdown/src/main/java/fr/eletutour/markdown/items/emphasis/Italic.java
  markdown/src/main/java/fr/eletutour/markdown/items/emphasis/README.md
  markdown/src/test/java/fr/eletutour/markdown/acceptance/steps/MarkdownGeneratorFileStepsDefinition.java
Labels: enhancement, good first issue, hacktoberfest-accepted

#20 add Bold Italic emphasis
  README.md
  markdown/src/main/java/fr/eletutour/markdown/items/emphasis/BoldItalic.java
  markdown/src/main/java/fr/eletutour/markdown/items/emphasis/README.md
  markdown/src/test/java/fr/eletutour/markdown/acceptance/steps/MarkdownGeneratorFileStepsDefinition.java
Labels: enhancement, good first issue, hacktoberfest-accepted

#21 add Strikethrough emphasis
  README.md
  markdown/src/main/java/fr/eletutour/markdown/items/emphasis/README.md
  markdown/src/main/java/fr/eletutour/markdown/items/emphasis/Strikethrough.java
  markdown/src/test/java/fr/eletutour/markdown/acceptance/steps/MarkdownGeneratorFileStepsDefinition.java
Labels: enhancement, good first issue, hacktoberfest-accepted
